// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://educveznypnobejyaial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdWN2ZXpueXBub2JlanlhaWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mzg5ODIsImV4cCI6MjA3MTExNDk4Mn0.JeBdB6nPGBRR03QS2Le5OdjOjw2V-05nOdhwiPS7Z8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});